Etude Alvarez
========================================================

La question de recherche est dans Read.me

ce qu'il ne faut pas faire...
- les données sont dans un classeur de 3 feuilles ce qui revient à traiter 3 fichiers => impossible en l'état de comparer les données, il faut fusionner les fichiers
- le sexe est sur 2 colonnes => faire une seule colonne H et F

```{r init}
file<-"QCM_2013_Qinitial.csv"
f1<-read.csv(file,header=TRUE,sep=",")

f1$Homme[!is.na(f1$Homme)]<-"H"
f1$Homme[is.na(f1$Homme)]<-"F"
f1$sexe[f1$Homme=="H"]<-"H"
f1$sexe[f1$Homme=="F"]<-"F"
f1<-f1[-3:-4]
# expérience SXP sans exp, XPM3 moins de 3 ans, XPP3 plu de 3 ans
f1$exp<-1:102
f1$exp[]
f1$exp[f1$Sans.XP==1]<-"SXP"
f1$exp[f1[6]==1]<-"XPM3"
f1$exp[f1[5]==1]<-"XPP3"
f1<-f1[-4:-6]
# origine
f1$origine<-NA
f1$origine[f1$Pro==1]<-"PRO"
f1$origine[f1$Assoc==1]<-"ASSOC"
f1$origine[f1$S.P.V==1]<-"SPV"
f1<-f1[-4:-6]
# pédagogie
f1$pedago<-NA
f1$pedago[f1$Active==1]<-"Active"
f1$pedago[f1$Passive==1]<-"Passive"
f1<-f1[-4:-5]
}
```

Comparaisons
```{r Q1}
table(f1$Q1i,f1$pedago)
chisq.test(t)
```
ccl: pas de différence entre les groupes au départ pour Q1
